### ISSUE TITLE
failed to compile complex three mutually recursive methods 

### ISSUE THREAD

**Issue by weihsiu** [wheaties/TwoTails#13] opened 2016-06-21 04:00 UTC
simple 3 mutually recursive methods compile and run correctly.  however, methods formulated like the ones below failed to comple with an error message:
`[error] (compile:compileIncremental) java.lang.NullPointerException`

``` scala
@mutualrec final def dog1(count: Int): Int = if (count == 0) count else dog2(count - 1)
@mutualrec final def dog2(count: Int): Int = if (count == 0) count else if (count % 2 == 0) dog1(count - 1) else dog3(count - 1)
@mutualrec final def dog3(count: Int): Int = if (count == 0) count else dog1(count - 1)
```

**Comment by wheaties** [comment] 2016-06-21 13:48
I can reproduce this and will be looking into it pronto.

**Comment by wheaties** [comment] 2016-06-22 13:45
This might take a while. I can't see anything obvious in the twotails phase. The error is happening in the `explicitouter` compiler phase. Any help would be greatly appreciated.

**Comment by wheaties** [comment] 2016-06-25 02:39
Don't even have to get that complicated:
```scala
class Cat{
  @mutualrec final def one(count: Int): Int = if (count < 0) 0 else two(count - 1)
  @mutualrec final def two(count: Int): Int = if (count < 0) 0 else {
  	val x = count-1
  	three(x-1)
  }
  @mutualrec final def three(count: Int): Int = if (count < 0) 0 else one(count - 1)
}
```

**Comment by naderghanbari** [comment] 2016-08-06 17:32
This happens even with just two mutually recursive functions:

```
@mutualrec final def dog1(count: Int): Int = if (count == 0) count else dog2(count - 1)
@mutualrec final def dog2(count: Int): Int = if (count == 0) count else if (count % 2 == 0) dog1(count - 1) else dog1(count - 2)
```

**Comment by wheaties** [comment] 2016-08-06 21:44
Well, that settles it. It's an issue with the nested `if` tree not having enough information to infer the result type.

**Comment by naderghanbari** [comment] 2016-08-06 22:55
For Scala `2.11.8` the actual `NPE` seems to be happening in the `scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preEraseAsInstanceOf$1(Erasure.scala:885)`

**Comment by wheaties** [comment] 2016-08-06 23:11
Yeah, it's a null type in the type tree. I can further reduce it to:

``` scala
final class Yoyoyo{
  @mutualrec def one(x: Int): Int = if(x < 0) x else two(x-1)
  @mutualrec def two(x: Int): Int = if(x < 0) one(x) else two(x-1)
}
```

Sorry if I mispoke that it was in explicitouter, that's the phase right before erasure.

**Comment by wheaties** [comment] 2016-11-12 19:24
Finally got a fix for this. Will publish a 0.3.0 this week.

**Closed as completed by wheaties** 2016-11-12 19:24 UTC
Labels: bug, help wanted
